trigger: none

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-tests.yml
  parameters:
    ServiceDirectory: storage
    BuildInParallel: true
    TimeoutInMinutes: 180
    Location: canadacentral
    CloudConfig:
      Public:
        SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
      PrivatePreview:
        SubscriptionConfiguration: $(sub-config-storage-test-resources)
    Clouds: Public
    SupportedClouds: Public,PrivatePreview
    TestSetupSteps:
    - template: /sdk/storage/tests-install-azurite.yml
    EnvVars:
      AZURE_ONLY_TEST_LATEST_SERVICE_VERSION: true
